# Generated by Django 4.1.1 on 2022-10-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g6', '0003_rename_reports_report_doctor_availability_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_availability',
            name='full',
            field=models.BooleanField(default=False),
        ),
    ]
