# Generated by Django 4.1.1 on 2022-10-12 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('g6', '0005_remove_appointment_date_remove_appointment_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='doctor',
            new_name='appointment_details',
        ),
    ]
