# Generated by Django 4.1.1 on 2022-10-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g6', '0006_rename_doctor_appointment_appointment_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor_availability',
            name='comment',
        ),
        migrations.AddField(
            model_name='appointment',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
