# Generated by Django 4.1.1 on 2022-10-13 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('g6', '0007_remove_doctor_availability_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='personal_doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='g6.doctor'),
            preserve_default=False,
        ),
    ]
