# Generated by Django 4.1.1 on 2022-10-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g6', '0008_report_personal_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.TimeField(max_length=200),
        ),
    ]
