# Generated by Django 4.1.1 on 2022-10-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g6', '0009_alter_report_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='contact_number',
            field=models.IntegerField(null=True),
        ),
    ]
