# Generated by Django 4.1.1 on 2023-02-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g6', '0010_patient_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='contact_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
