# Generated by Django 4.1.1 on 2023-02-15 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('g6', '0011_alter_patient_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='contact_number',
        ),
    ]
